DROP DATABASE if EXISTS LMD_Avions;

CREATE DATABASE LMD_Avions;

USE LMD_Avions;

CREATE TABLE AVIONS(
	AV INTEGER NOT NULL AUTO_INCREMENT,
	AVMARQUE VARCHAR(50) NOT NULL,
	AVTYPE VARCHAR(50) NOT NULL,
	CAP INTEGER NOT NULL,
	LOC VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (AV)
);

CREATE TABLE PILOTES(
	PIL INTEGER NOT NULL AUTO_INCREMENT,
	PILNOM VARCHAR(50) NOT NULL,
	ADR VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (PIL)
);

CREATE TABLE VOLS(
	VOL INTEGER NOT NULL AUTO_INCREMENT,
	PIL INTEGER NOT NULL,
	AV INTEGER NOT NULL,
	VD VARCHAR(50) NOT NULL,
	VA VARCHAR(50) NOT NULL,
	HD TIME NOT NULL,
	HA TIME NOT NULL,
	
	PRIMARY KEY (VOL)
);

ALTER TABLE AVIONS
	AUTO_INCREMENT = 100
;

ALTER TABLE VOLS
	AUTO_INCREMENT = 100, 
	ADD CONSTRAINT FK_VOLS_PILOTES FOREIGN KEY (PIL) REFERENCES PILOTES(PIL),
	ADD CONSTRAINT FK_VOLS_AVIONS FOREIGN KEY (AV) REFERENCES AVIONS(AV)
;


