DROP DATABASE if EXISTS LDD_Ex4;

CREATE DATABASE LDD_Ex4;

USE LDD_Ex4;

CREATE TABLE Livres(
	ISBN INTEGER NOT NULL,
	Titre VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (ISBN)
);

CREATE TABLE Exemplaires(
	num_Exempl INTEGER NOT NULL,
	ISBN INTEGER NOT NULL,
	Etat CHAR(1) NOT NULL DEFAULT 'D',
	
	PRIMARY KEY (num_Exempl, ISBN)
);

ALTER TABLE Exemplaires
	ADD CONSTRAINT CHECK (Etat IN ('D', 'E', 'P')),
	ADD CONSTRAINT FK_Exemplaires_Livres FOREIGN KEY (ISBN) REFERENCES Livres(ISBN)
;