DROP DATABASE if EXISTS LDD_Ex6;

CREATE DATABASE LDD_Ex6;

USE LDD_Ex6;

CREATE TABLE Rayons(
	NomR VARCHAR(50) NOT NULL AUTO_INCREMENT,
	Etage INTEGER NOT NULL,
	
	PRIMARY KEY (NomR)
);

CREATE TABLE Employes(
	CodeE INTEGER NOT NULL,
	Nom VARCHAR(50) NOT NULL,
	Salaire DECIMAL(12,2) NOT NULL,
	CodeE_chef INTEGER,
	NomR VARCHAR(50),
	
	PRIMARY KEY (CodeE),
);

ALTER TABLE Employes ADD 
	CONSTRAINT FK_Employes_Employes FOREIGN KEY (CodeE_chef) REFERENCES Employes(CodeE),
	CONSTRAINT FK_Employes_Rayons FOREIGN KEY (NomR) REFERENCES Rayons(NomR);

CREATE INDEX IX_Nom ON Employes(Nom);

CREATE TABLE Articles(
	CodeA INTEGER NOT NULL,
	NomA VARCHAR(50) NOT NULL,
	TypeA CHAR(1) NOT NULL,
	NomR VARCHAR(50),
	
	PRIMARY KEY (CodeA),
	CONSTRAINT FK_Rayons FOREIGN KEY (NomR) REFERENCES Rayons(NomR)
);

CREATE TABLE Fournisseurs(
	CodeF INTEGER NOT NULL,
	Adresse VARCHAR(50) NOT NULL,
	NomF VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_CodeF PRIMARY KEY (CodeF)
);

CREATE TABLE Livraisons(
	CodeF INTEGER NOT NULL,
	CodeA INTEGER NOT NULL,
	Quantite INTEGER NOT NULL,
	
	CONSTRAINT PK_Code PRIMARY KEY (CodeF, CodeA),
	CONSTRAINT FK_Fournisseurs FOREIGN KEY (CodeF) REFERENCES Fournisseurs(CodeF),
	CONSTRAINT FK_Articles FOREIGN KEY (CodeA) REFERENCES Articles(CodeA)
);

