DROP DATABASE if EXISTS LDD_Ex1;

CREATE DATABASE LDD_Ex1;

USE LDD_Ex1;

CREATE TABLE Personnes(
	id_Personne INTEGER NOT NULL AUTO_INCREMENT,
	Nom VARCHAR(50) NOT NULL,
	Prenom VARCHAR(50) NOT NULL,
	No_rue INTEGER NOT NULL,
	Rue VARCHAR(50) NOT NULL,
	CP INTEGER NOT NULL,
	Ville VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (id_Personne)
);

CREATE TABLE Vehicules(
	immatriculation INTEGER NOT NULL AUTO_INCREMENT,
	Marque VARCHAR(50) NOT NULL,
	kilometrage INTEGER NOT NULL,
	Date_mise_en_service DATE NOT NULL,
	id_Personne INTEGER NOT NULL,
	
	PRIMARY KEY (immatriculation)
);

ALTER TABLE Personnes
	ADD CONSTRAINT CK_Personnes_CP CHECK (CP < 96000)
;

ALTER TABLE Vehicules
	ADD CONSTRAINT FK_Personnes FOREIGN KEY (id_Personne) REFERENCES Personnes(id_Personne)
;